In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
type (arr)

numpy.ndarray

In [3]:
arr.shape

(3,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [6]:
arr3.shape

(2, 2, 3)